# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: 
    displayName: build
    steps:
      - task: GoTool@0
        inputs:
          version: '1.14'
      - task: Go@0
        inputs:
          command: 'get'
          arguments: '-d ./...'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
      - task: Go@0
        inputs:
          command: 'build'
          arguments: './...'
          workingDirectory: '$(System.DefaultWorkingDirectory)'

  - job: 
    displayName: unit-test
    steps:
      - task: GoTool@0
        inputs:
          version: '1.14'
      - task: Go@0
        inputs:
          command: 'get'
          arguments: '-d ./...'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
      - task: Go@0
        inputs:
          command: 'test'
          arguments: '-v ./... -cover'
          workingDirectory: '$(System.DefaultWorkingDirectory)'

  - job:
    displayName: integration-test
    strategy:
      matrix:
        FABRIC_20:
          FABRIC_VERSION: '22'
          INTERGATION_CASE: 'ANDLogic'
        FABRIC_20_ORLogic:
          FABRIC_VERSION: '22'
          INTERGATION_CASE: 'ORLogic'
        FABRIC_14:
          FABRIC_VERSION: '14'
          INTERGATION_CASE: 'ANDLogic'
        LATEST:
          FABRIC_VERSION: ''
    steps:
      - script: ./test/integration-test.sh $(FABRIC_VERSION) $(INTERGATION_CASE)
