# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  - master

variables:
  GOPATH: $(Agent.BuildDirectory)/go
  PATH: $(Agent.BuildDirectory)/go/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin

jobs:
  - job: ut
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-latest'
        mac:
          imageName: 'macOS-latest'
#        windows:
#          imageName: 'windows-latest'
    displayName: ut
    pool:
      vmImage: $(imageName)
    steps:
      - task: CMake@1
        displayName: install make tool
      - task: GoTool@0
        inputs:
          version: '1.14'
        displayName: install go
      - script: make basic-checks
        displayName: run basic checks like linter
      - script: make tape
        displayName: build tape binary program
      - script: make install
        displayName: install tape to GOBIN
      - script: make unit-test
        displayName: run unit test

  - job: dockerbuild
    displayName: dockerbuild
    steps:
    - script: make docker
      displayName: build tape docker

  - job: integrationTest
    displayName: integrationTest
    dependsOn:
    - ut
    - dockerbuild
    strategy:
      matrix:
        FABRIC_2_2:
          FABRIC_VERSION: '2_2'
          INTERGATION_CASE: 'ANDLogic'
        FABRIC_2_2_ORLogic:
          FABRIC_VERSION: '2_2'
          INTERGATION_CASE: 'ORLogic'
        FABRIC_2_3:
          FABRIC_VERSION: '2_3'
          INTERGATION_CASE: 'ANDLogic'
        FABRIC_2_3_ORLogic:
          FABRIC_VERSION: '2_3'
          INTERGATION_CASE: 'ORLogic'
        FABRIC_1_4:
          FABRIC_VERSION: '1_4'
          INTERGATION_CASE: 'ANDLogic'
        LATEST:
          FABRIC_VERSION: 'latest'
          INTERGATION_CASE: 'ANDLogic'
    steps:
      - script: make integration-test FABRIC_VERSION=$(FABRIC_VERSION) INTERGATION_CASE=$(INTERGATION_CASE)

  - job: BuildAndReleaseBinaries
    displayName: BuildAndReleaseBinaries
    dependsOn:
      - integrationTest
    steps:
      - script: GOOS=linux GOARCH=amd64 make tape && cp tape linux-amd64 && cp config.yaml linux-amd64 && tar -czvf "tape-linux-amd64.tar.gz" linux-amd64 && GOOS=darwin GOARCH=amd64 make tape && cp tape darwin-amd64 && cp config.yaml darwin-amd64 && tar -czvf "tape-darwin-amd64.tar.gz" darwin-amd64 && GOOS=windows GOARCH=amd64 make tape && cp tape windows-amd64 && cp config.yaml windows-amd64 && tar -czvf "tape-windows-amd64.tar.gz" windows-amd64
        displayName: Compile Binary and Create Tarball
      - task: GithubRelease@0
        displayName: 'Create GitHub Release'
        inputs:
          repositoryName: '$(Build.Repository.Name)'
          gitHubConnection: github.com_stone-ch
          action: 'create'
          tagSource: 'auto'
          tagPattern: 'v.*'
          assets: |
            ./*.tar.gz
