# Definition of nodes
peer1: &peer1
  addr: peer0.org1.example.com:7051
  tls_ca_cert: /data/fabric/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem

peer2: &peer2
  addr: peer0.org2.example.com:8051
  tls_ca_cert: /data/fabric/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem

orderer1: &orderer1
  addr: orderer0.example.com:7050
  tls_ca_cert: /data/fabric/crypto-config/ordererOrganizations/example.com/msp/tlscacerts/tlsca.example.com-cert.pem

# Nodes to interact with
endorsers:
  - *peer1
  - *peer2
# we might support multi-committer in the future for more complex test scenario,
# i.e. consider tx committed only if it's done on >50% of nodes. But for now,
# it seems sufficient to support single committer.
committers: 
  - *peer1
  - *peer2
commitThreshold: 2
orderer: *orderer1

# Invocation configs
channel: cloudchain
chaincode: universal-deposit
args:
  - GetApplicationInfo
  - 112
mspid: Org1MSP
private_key: /data/fabric/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/b15f788c65d78fd141ef8a1cebd98af12b588505cdbe9fc6a077e1e88a82d250_sk
sign_cert: /data/fabric/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem
num_of_conn: 10
client_per_conn: 10
