name: dailyImageBuild

on:
  schedule:
    - cron: "0 7 * * *" # https://crontab.guru/#0_0_*_*_0

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: davidkhala
          password: ${{ secrets.TWGC_DAVIDKHALA }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: ghcr.io/hyperledger-twgc/tape
          tags: |
            type=ref,event=tag
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/s390x
          push: true
          tags: ghcr.io/hyperledger-twgc/tape
          labels: latest
